<?php
/*
 * Function to register a new field for user's country
 *
 * @since 2.2.28
 * @returns void
 */

function ninja_forms_register_field_country(){
	$countries = array(
		"- Select One" => "",
		"Afghanistan" => "AF",
		"Albania" => "AL",
		"Algeria" => "DZ",
		"American Samoa" => "AS",
		"Andorra" => "AD",
		"Angola" => "AO",
		"Anguilla" => "AI",
		"Antarctica" => "AQ",
		"Antigua And Barbuda" => "AG",
		"Argentina" => "AR",
		"Armenia" => "AM",
		"Aruba" => "AW",
		"Australia" => "AU",
		"Austria" => "AT",
		"Azerbaijan" => "AZ",
		"Bahamas" => "BS",
		"Bahrain" => "BH",
		"Bangladesh" => "BD",
		"Barbados" => "BB",
		"Belarus" => "BY",
		"Belgium" => "BE",
		"Belize" => "BZ",
		"Benin" => "BJ",
		"Bermuda" => "BM",
		"Bhutan" => "BT",
		"Bolivia" => "BO",
		"Bosnia And Herzegowina" => "BA",
		"Botswana" => "BW",
		"Bouvet Island" => "BV",
		"Brazil" => "BR",
		"British Indian Ocean Territory" => "IO",
		"Brunei Darussalam" => "BN",
		"Bulgaria" => "BG",
		"Burkina Faso" => "BF",
		"Burundi" => "BI",
		"Cambodia" => "KH",
		"Cameroon" => "CM",
		"Canada" => "CA",
		"Cape Verde" => "CV",
		"Cayman Islands" => "KY",
		"Central African Republic" => "CF",
		"Chad" => "TD",
		"Chile" => "CL",
		"China" => "CN",
		"Christmas Island" => "CX",
		"Cocos (Keeling) Islands" => "CC",
		"Colombia" => "CO",
		"Comoros" => "KM",
		"Congo" => "CG",
		"Congo, The Democratic Republic Of The" => "CD",
		"Cook Islands" => "CK",
		"Costa Rica" => "CR",
		"Cote D'Ivoire" => "CI",
		"Croatia (Local Name: Hrvatska)" => "HR",
		"Cuba" => "CU",
		"Cyprus" => "CY",
		"Czech Republic" => "CZ",
		"Denmark" => "DK",
		"Djibouti" => "DJ",
		"Dominica" => "DM",
		"Dominican Republic" => "DO",
		"East Timor" => "TP",
		"Ecuador" => "EC",
		"Egypt" => "EG",
		"El Salvador" => "SV",
		"Equatorial Guinea" => "GQ",
		"Eritrea" => "ER",
		"Estonia" => "EE",
		"Ethiopia" => "ET",
		"Falkland Islands (Malvinas)" => "FK",
		"Faroe Islands" => "FO",
		"Fiji" => "FJ",
		"Finland" => "FI",
		"France" => "FR",
		"France, Metropolitan" => "FX",
		"French Guiana" => "GF",
		"French Polynesia" => "PF",
		"French Southern Territories" => "TF",
		"Gabon" => "GA",
		"Gambia" => "GM",
		"Georgia" => "GE",
		"Germany" => "DE",
		"Ghana" => "GH",
		"Gibraltar" => "GI",
		"Greece" => "GR",
		"Greenland" => "GL",
		"Grenada" => "GD",
		"Guadeloupe" => "GP",
		"Guam" => "GU",
		"Guatemala" => "GT",
		"Guinea" => "GN",
		"Guinea-Bissau" => "GW",
		"Guyana" => "GY",
		"Haiti" => "HT",
		"Heard And Mc Donald Islands" => "HM",
		"Holy See (Vatican City State)" => "VA",
		"Honduras" => "HN",
		"Hong Kong" => "HK",
		"Hungary" => "HU",
		"Iceland" => "IS",
		"India" => "IN",
		"Indonesia" => "ID",
		"Iran (Islamic Republic Of)" => "IR",
		"Iraq" => "IQ",
		"Ireland" => "IE",
		"Israel" => "IL",
		"Italy" => "IT",
		"Jamaica" => "JM",
		"Japan" => "JP",
		"Jordan" => "JO",
		"Kazakhstan" => "KZ",
		"Kenya" => "KE",
		"Kiribati" => "KI",
		"Korea, Democratic People's Republic Of" => "KP",
		"Korea, Republic Of" => "KR",
		"Kuwait" => "KW",
		"Kyrgyzstan" => "KG",
		"Lao People's Democratic Republic" => "LA",
		"Latvia" => "LV",
		"Lebanon" => "LB",
		"Lesotho" => "LS",
		"Liberia" => "LR",
		"Libyan Arab Jamahiriya" => "LY",
		"Liechtenstein" => "LI",
		"Lithuania" => "LT",
		"Luxembourg" => "LU",
		"Macau" => "MO",
		"Macedonia, Former Yugoslav Republic Of" => "MK",
		"Madagascar" => "MG",
		"Malawi" => "MW",
		"Malaysia" => "MY",
		"Maldives" => "MV",
		"Mali" => "ML",
		"Malta" => "MT",
		"Marshall Islands" => "MH",
		"Martinique" => "MQ",
		"Mauritania" => "MR",
		"Mauritius" => "MU",
		"Mayotte" => "YT",
		"Mexico" => "MX",
		"Micronesia, Federated States Of" => "FM",
		"Moldova, Republic Of" => "MD",
		"Monaco" => "MC",
		"Mongolia" => "MN",
		"Montserrat" => "MS",
		"Morocco" => "MA",
		"Mozambique" => "MZ",
		"Myanmar" => "MM",
		"Namibia" => "NA",
		"Nauru" => "NR",
		"Nepal" => "NP",
		"Netherlands" => "NL",
		"Netherlands Antilles" => "AN",
		"New Caledonia" => "NC",
		"New Zealand" => "NZ",
		"Nicaragua" => "NI",
		"Niger" => "NE",
		"Nigeria" => "NG",
		"Niue" => "NU",
		"Norfolk Island" => "NF",
		"Northern Mariana Islands" => "MP",
		"Norway" => "NO",
		"Oman" => "OM",
		"Pakistan" => "PK",
		"Palau" => "PW",
		"Panama" => "PA",
		"Papua New Guinea" => "PG",
		"Paraguay" => "PY",
		"Peru" => "PE",
		"Philippines" => "PH",
		"Pitcairn" => "PN",
		"Poland" => "PL",
		"Portugal" => "PT",
		"Puerto Rico" => "PR",
		"Qatar" => "QA",
		"Reunion" => "RE",
		"Romania" => "RO",
		"Russian Federation" => "RU",
		"Rwanda" => "RW",
		"Saint Kitts And Nevis" => "KN",
		"Saint Lucia" => "LC",
		"Saint Vincent And The Grenadines" => "VC",
		"Samoa" => "WS",
		"San Marino" => "SM",
		"Sao Tome And Principe" => "ST",
		"Saudi Arabia" => "SA",
		"Senegal" => "SN",
		"Seychelles" => "SC",
		"Sierra Leone" => "SL",
		"Singapore" => "SG",
		"Slovakia (Slovak Republic)" => "SK",
		"Slovenia" => "SI",
		"Solomon Islands" => "SB",
		"Somalia" => "SO",
		"South Africa" => "ZA",
		"South Georgia, South Sandwich Islands" => "GS",
		"Spain" => "ES",
		"Sri Lanka" => "LK",
		"St. Helena" => "SH",
		"St. Pierre And Miquelon" => "PM",
		"Sudan" => "SD",
		"Suriname" => "SR",
		"Svalbard And Jan Mayen Islands" => "SJ",
		"Swaziland" => "SZ",
		"Sweden" => "SE",
		"Switzerland" => "CH",
		"Syrian Arab Republic" => "SY",
		"Taiwan" => "TW",
		"Tajikistan" => "TJ",
		"Tanzania, United Republic Of" => "TZ",
		"Thailand" => "TH",
		"Togo" => "TG",
		"Tokelau" => "TK",
		"Tonga" => "TO",
		"Trinidad And Tobago" => "TT",
		"Tunisia" => "TN",
		"Turkey" => "TR",
		"Turkmenistan" => "TM",
		"Turks And Caicos Islands" => "TC",
		"Tuvalu" => "TV",
		"Uganda" => "UG",
		"Ukraine" => "UA",
		"United Arab Emirates" => "AE",
		"United Kingdom" => "GB",
		"United States" => "US",
		"United States Minor Outlying Islands" => "UM",
		"Uruguay" => "UY",
		"Uzbekistan" => "UZ",
		"Vanuatu" => "VU",
		"Venezuela" => "VE",
		"Viet Nam" => "VN",
		"Virgin Islands (British)" => "VG",
		"Virgin Islands (U.S.)" => "VI",
		"Wallis And Futuna Islands" => "WF",
		"Western Sahara" => "EH",
		"Yemen" => "YE",
		"Yugoslavia" => "YU",
		"Zambia" => "ZM",
		"Zimbabwe" => "ZW"
	);
	
	$tmp_array = array();
	foreach ( $countries as $country => $abbr ) {
		$tmp_array[] = array( 'name' => $country, 'value' => $abbr );
	}
	$args = array(
		'name' => 'Country',
		'sidebar' => '',
		'display_function' => 'ninja_forms_field_country_display',
		'group' => 'standard_fields',
		'edit_conditional' => true,
		'edit_options' => array(
			array(
				'type' => 'select',
				'name' => 'default_value',
				'label' => __( 'Default Country', 'ninja-forms' ),
				'class' => 'widefat',
				'options' => $tmp_array,
			),
			array(
				'type' => 'checkbox',
				'name' => 'country_use_custom_first',
				'label' => __( 'Use a custom first option', 'ninja-forms' ),
				'width' => 'thin',
			),
			array(
				'type' => 'text',
				'name' => 'country_custom_first',
				'label' => __( 'Custom first option', 'ninja-forms' ),
				'width' => 'thin',
				'class' => 'widefat',
			),
			array(
				'type' => 'hidden',
				'name' => 'user_info_field_group',
				'default' => 1,
			),
		),
		'conditional' => array(
			'value' => array(
				'type' => 'select',
				'options' => $countries,
			),
		),
	);

	ninja_forms_register_field( '_country', $args );
}

add_action( 'init', 'ninja_forms_register_field_country' );

/*
 * Function to display our country field on the front-end.
 *
 * @since 2.2.30
 * @returns void
 */

function ninja_forms_field_country_display( $field_id, $data ) {
	$countries = array(
		"Afghanistan" => "AF",
		"Albania" => "AL",
		"Algeria" => "DZ",
		"American Samoa" => "AS",
		"Andorra" => "AD",
		"Angola" => "AO",
		"Anguilla" => "AI",
		"Antarctica" => "AQ",
		"Antigua And Barbuda" => "AG",
		"Argentina" => "AR",
		"Armenia" => "AM",
		"Aruba" => "AW",
		"Australia" => "AU",
		"Austria" => "AT",
		"Azerbaijan" => "AZ",
		"Bahamas" => "BS",
		"Bahrain" => "BH",
		"Bangladesh" => "BD",
		"Barbados" => "BB",
		"Belarus" => "BY",
		"Belgium" => "BE",
		"Belize" => "BZ",
		"Benin" => "BJ",
		"Bermuda" => "BM",
		"Bhutan" => "BT",
		"Bolivia" => "BO",
		"Bosnia And Herzegowina" => "BA",
		"Botswana" => "BW",
		"Bouvet Island" => "BV",
		"Brazil" => "BR",
		"British Indian Ocean Territory" => "IO",
		"Brunei Darussalam" => "BN",
		"Bulgaria" => "BG",
		"Burkina Faso" => "BF",
		"Burundi" => "BI",
		"Cambodia" => "KH",
		"Cameroon" => "CM",
		"Canada" => "CA",
		"Cape Verde" => "CV",
		"Cayman Islands" => "KY",
		"Central African Republic" => "CF",
		"Chad" => "TD",
		"Chile" => "CL",
		"China" => "CN",
		"Christmas Island" => "CX",
		"Cocos (Keeling) Islands" => "CC",
		"Colombia" => "CO",
		"Comoros" => "KM",
		"Congo" => "CG",
		"Congo, The Democratic Republic Of The" => "CD",
		"Cook Islands" => "CK",
		"Costa Rica" => "CR",
		"Cote D'Ivoire" => "CI",
		"Croatia (Local Name: Hrvatska)" => "HR",
		"Cuba" => "CU",
		"Cyprus" => "CY",
		"Czech Republic" => "CZ",
		"Denmark" => "DK",
		"Djibouti" => "DJ",
		"Dominica" => "DM",
		"Dominican Republic" => "DO",
		"East Timor" => "TP",
		"Ecuador" => "EC",
		"Egypt" => "EG",
		"El Salvador" => "SV",
		"Equatorial Guinea" => "GQ",
		"Eritrea" => "ER",
		"Estonia" => "EE",
		"Ethiopia" => "ET",
		"Falkland Islands (Malvinas)" => "FK",
		"Faroe Islands" => "FO",
		"Fiji" => "FJ",
		"Finland" => "FI",
		"France" => "FR",
		"France, Metropolitan" => "FX",
		"French Guiana" => "GF",
		"French Polynesia" => "PF",
		"French Southern Territories" => "TF",
		"Gabon" => "GA",
		"Gambia" => "GM",
		"Georgia" => "GE",
		"Germany" => "DE",
		"Ghana" => "GH",
		"Gibraltar" => "GI",
		"Greece" => "GR",
		"Greenland" => "GL",
		"Grenada" => "GD",
		"Guadeloupe" => "GP",
		"Guam" => "GU",
		"Guatemala" => "GT",
		"Guinea" => "GN",
		"Guinea-Bissau" => "GW",
		"Guyana" => "GY",
		"Haiti" => "HT",
		"Heard And Mc Donald Islands" => "HM",
		"Holy See (Vatican City State)" => "VA",
		"Honduras" => "HN",
		"Hong Kong" => "HK",
		"Hungary" => "HU",
		"Iceland" => "IS",
		"India" => "IN",
		"Indonesia" => "ID",
		"Iran (Islamic Republic Of)" => "IR",
		"Iraq" => "IQ",
		"Ireland" => "IE",
		"Israel" => "IL",
		"Italy" => "IT",
		"Jamaica" => "JM",
		"Japan" => "JP",
		"Jordan" => "JO",
		"Kazakhstan" => "KZ",
		"Kenya" => "KE",
		"Kiribati" => "KI",
		"Korea, Democratic People's Republic Of" => "KP",
		"Korea, Republic Of" => "KR",
		"Kuwait" => "KW",
		"Kyrgyzstan" => "KG",
		"Lao People's Democratic Republic" => "LA",
		"Latvia" => "LV",
		"Lebanon" => "LB",
		"Lesotho" => "LS",
		"Liberia" => "LR",
		"Libyan Arab Jamahiriya" => "LY",
		"Liechtenstein" => "LI",
		"Lithuania" => "LT",
		"Luxembourg" => "LU",
		"Macau" => "MO",
		"Macedonia, Former Yugoslav Republic Of" => "MK",
		"Madagascar" => "MG",
		"Malawi" => "MW",
		"Malaysia" => "MY",
		"Maldives" => "MV",
		"Mali" => "ML",
		"Malta" => "MT",
		"Marshall Islands" => "MH",
		"Martinique" => "MQ",
		"Mauritania" => "MR",
		"Mauritius" => "MU",
		"Mayotte" => "YT",
		"Mexico" => "MX",
		"Micronesia, Federated States Of" => "FM",
		"Moldova, Republic Of" => "MD",
		"Monaco" => "MC",
		"Mongolia" => "MN",
		"Montserrat" => "MS",
		"Morocco" => "MA",
		"Mozambique" => "MZ",
		"Myanmar" => "MM",
		"Namibia" => "NA",
		"Nauru" => "NR",
		"Nepal" => "NP",
		"Netherlands" => "NL",
		"Netherlands Antilles" => "AN",
		"New Caledonia" => "NC",
		"New Zealand" => "NZ",
		"Nicaragua" => "NI",
		"Niger" => "NE",
		"Nigeria" => "NG",
		"Niue" => "NU",
		"Norfolk Island" => "NF",
		"Northern Mariana Islands" => "MP",
		"Norway" => "NO",
		"Oman" => "OM",
		"Pakistan" => "PK",
		"Palau" => "PW",
		"Panama" => "PA",
		"Papua New Guinea" => "PG",
		"Paraguay" => "PY",
		"Peru" => "PE",
		"Philippines" => "PH",
		"Pitcairn" => "PN",
		"Poland" => "PL",
		"Portugal" => "PT",
		"Puerto Rico" => "PR",
		"Qatar" => "QA",
		"Reunion" => "RE",
		"Romania" => "RO",
		"Russian Federation" => "RU",
		"Rwanda" => "RW",
		"Saint Kitts And Nevis" => "KN",
		"Saint Lucia" => "LC",
		"Saint Vincent And The Grenadines" => "VC",
		"Samoa" => "WS",
		"San Marino" => "SM",
		"Sao Tome And Principe" => "ST",
		"Saudi Arabia" => "SA",
		"Senegal" => "SN",
		"Seychelles" => "SC",
		"Sierra Leone" => "SL",
		"Singapore" => "SG",
		"Slovakia (Slovak Republic)" => "SK",
		"Slovenia" => "SI",
		"Solomon Islands" => "SB",
		"Somalia" => "SO",
		"South Africa" => "ZA",
		"South Georgia, South Sandwich Islands" => "GS",
		"Spain" => "ES",
		"Sri Lanka" => "LK",
		"St. Helena" => "SH",
		"St. Pierre And Miquelon" => "PM",
		"Sudan" => "SD",
		"Suriname" => "SR",
		"Svalbard And Jan Mayen Islands" => "SJ",
		"Swaziland" => "SZ",
		"Sweden" => "SE",
		"Switzerland" => "CH",
		"Syrian Arab Republic" => "SY",
		"Taiwan" => "TW",
		"Tajikistan" => "TJ",
		"Tanzania, United Republic Of" => "TZ",
		"Thailand" => "TH",
		"Togo" => "TG",
		"Tokelau" => "TK",
		"Tonga" => "TO",
		"Trinidad And Tobago" => "TT",
		"Tunisia" => "TN",
		"Turkey" => "TR",
		"Turkmenistan" => "TM",
		"Turks And Caicos Islands" => "TC",
		"Tuvalu" => "TV",
		"Uganda" => "UG",
		"Ukraine" => "UA",
		"United Arab Emirates" => "AE",
		"United Kingdom" => "GB",
		"United States" => "US",
		"United States Minor Outlying Islands" => "UM",
		"Uruguay" => "UY",
		"Uzbekistan" => "UZ",
		"Vanuatu" => "VU",
		"Venezuela" => "VE",
		"Viet Nam" => "VN",
		"Virgin Islands (British)" => "VG",
		"Virgin Islands (U.S.)" => "VI",
		"Wallis And Futuna Islands" => "WF",
		"Western Sahara" => "EH",
		"Yemen" => "YE",
		"Yugoslavia" => "YU",
		"Zambia" => "ZM",
		"Zimbabwe" => "ZW"
	);

	if( isset( $data['default_value'] ) ) {
		$default_value = $data['default_value'];
	}else{
		$default_value = '';
	}

	if ( isset ( $data['country_custom_first'] ) ) {
		$country_custom_first = $data['country_custom_first'];
	} else {
		$country_custom_first = '';
	}

	if ( isset ( $data['country_use_custom_first'] ) AND $data['country_use_custom_first'] == 1 ) {
		$countries = array_merge( array( $country_custom_first => $country_custom_first ), $countries );
	}

	$field_class = ninja_forms_get_field_class( $field_id );
	?>

	<input type="hidden" id="ninja_forms_field_<?php echo $field_id;?>_list_type" value="dropdown">
	<select name="ninja_forms_field_<?php echo $field_id;?>" id="ninja_forms_field_<?php echo $field_id;?>" rel="<?php echo $field_id;?>" class="<?php echo $field_class;?>">
		<?php
		foreach ( $countries as $country => $abbr ) {
			?>
			<option value="<?php echo $abbr;?>" <?php selected( $abbr, $default_value );?>><?php echo $country;?></option>
			<?php
		}
	?>
	</select>

	<?php
}

/*
 *
 * Function that filters the hidden field output by display that identifies the field type.
 * This is a work around and will need to be removed once proper field registration is in place.
 *
 * @since 2.2.30
 * @returns string $field_type
 */

function ninja_forms_field_country_type_filter( $field_type, $field_id ) {
	$field = ninja_forms_get_field_by_id( $field_id );
	if ( $field['type'] == '_country' ) {
		$field_type = 'list';
	}
	
	return $field_type;
}

add_action( 'ninja_forms_display_field_type', 'ninja_forms_field_country_type_filter', 10, 2 );